# This workflow runs tests on every push. By doing that we ensure that everything is buildable.

name: Test
on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.1.1

      - name: configure node 21
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      - name: configure node 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      - name: configure node 14
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
